name: Build and Dploy Code

on: [push, pull_request]

jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v2
      - name: say hi to jas
        run: echo "Hi Jas!"